language: node_js
node_js:
  - "0.12"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/jspm config registries.github.auth $GH_TOKEN
  - ./node_modules/.bin/jspm install